name: 'trade_pipeline'
version: '1.0.0'
config-version: 2

profile: 'trade_pipeline'

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

clean-targets: ["target", "dbt_packages"]

models:
  trade_pipeline:
    staging:
      +schema: BRONZE
      +materialized: table
    intermediate:
      +schema: SILVER
      +materialized: table
    marts:
      +schema: GOLD
      +materialized: table
