CREATE FILE FORMAT IF NOT EXISTS TRADE_DB.RAW.JSON_FILE_FORMAT
    TYPE = JSON
    STRIP_OUTER_ARRAY = TRUE;

CREATE STAGE IF NOT EXISTS TRADE_DB.RAW.TRADE_STAGE
    FILE_FORMAT = TRADE_DB.RAW.JSON_FILE_FORMAT;